<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No_sd-btn sd-navigation__next-btn</name>
   <tag></tag>
   <elementGuidId>091c6726-b6b4-4e50-b4e2-43f529574425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sd-btn.sd-navigation__next-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5f4d06e-053a-4a07-a2c6-d96ddfa61dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b1267ad-f742-4783-96df-9bae1ccd45a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>event: { mousedown: nextPageMouseDown }, value: locPageNextText.koRenderedHtml, click: nextPageUIClick, visible: isShowNextButton, css: cssNavigationNext</value>
      <webElementGuid>31a62488-1ecb-40e7-a4d5-ff8cf3d1a159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>1b8e2fb9-a56c-467d-8ba2-ca7decd07633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sd-btn sd-navigation__next-btn</value>
      <webElementGuid>d205f174-0189-4d63-883e-0ef2b8171d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;surveyElement&quot;)/div[@class=&quot;sd-root-modern&quot;]/form[1]/div[@class=&quot;sd-container-modern&quot;]/div[@class=&quot;sd-body sd-body--static&quot;]/div[@class=&quot;sd-footer sd-body__navigation sd-clearfix&quot;]/input[@class=&quot;sd-btn sd-navigation__next-btn&quot;]</value>
      <webElementGuid>ad65333a-ef14-4edd-8e11-d763c4241f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Next']</value>
      <webElementGuid>f43d8d71-3023-46b3-a8f0-61c9f5f0600d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='surveyElement']/div/form/div[2]/div/div[2]/input[3]</value>
      <webElementGuid>d577f6aa-6f8d-4c01-b218-64061842e274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>1546c6a7-ae6e-463e-98f5-06f3bb83e8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>c1944e60-b419-4704-9320-fc5df521dfc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
