<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clinical  Outpatient treatment</name>
   <tag></tag>
   <elementGuidId>0a287838-d685-4731-8da8-33a1d4c06639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.claimques--claimType--title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ClaimQues1']/div[3]/div/a/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93c8206c-5d52-47f9-8684-f27e60244673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>claimques--claimType--title</value>
      <webElementGuid>4aeba4ab-0769-41cc-8aaa-39bbe715b5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clinical / Outpatient treatment </value>
      <webElementGuid>18b912a0-5dfd-401a-ae5a-fdddffff4827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClaimQues1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-6&quot;]/a[1]/div[@class=&quot;claimques--claimType&quot;]/div[@class=&quot;claimques--claimType--right&quot;]/div[@class=&quot;claimques--claimType--title&quot;]</value>
      <webElementGuid>97b55b6a-4fa0-4efa-b424-38b30cb33de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ClaimQues1']/div[3]/div/a/div/div[2]/div</value>
      <webElementGuid>8a621f34-8f6d-4118-a6a5-3a9b4fd30b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All claims must be submitted within 90 calendar days after discharge, surgery or treatment.'])[1]/following::div[6]</value>
      <webElementGuid>b81f254a-b93b-47ca-988f-0ae6a0a92628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What kind of medical expenses do you need to claim for?'])[1]/following::div[7]</value>
      <webElementGuid>bf271eda-0745-410a-9694-f20d8490c74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospitalisation / Inpatient treatment'])[1]/preceding::div[3]</value>
      <webElementGuid>6241af31-8321-4a67-8117-96a4b251bf7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clinical / Outpatient treatment']/parent::*</value>
      <webElementGuid>01471da5-720b-40bf-b232-f4a54c86b206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]/div</value>
      <webElementGuid>ddd5bdcd-a879-42e1-96ff-e06d524ec34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Clinical / Outpatient treatment ' or . = 'Clinical / Outpatient treatment ')]</value>
      <webElementGuid>ba7b7af6-6734-4e97-a3b2-c475ab3d5ed3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
