<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next1</name>
   <tag></tag>
   <elementGuidId>a781826e-4a10-4941-9fba-10b2b8f79e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='go_Enroll']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___widget > span.iconButton-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>48a73ac7-238d-4ba4-a958-f2bcc556ec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconButton-label</value>
      <webElementGuid>9b387f72-60b0-4546-bd4d-c71cf1d9249a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-guide-button-label</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>932b94da-8e48-463e-b927-60217c00844e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>d57e9f06-940d-4a57-b0f9-5864a5ba4efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___widget&quot;)/span[@class=&quot;iconButton-label&quot;]</value>
      <webElementGuid>1a74a413-4ca3-4953-9612-af33e92d254b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___widget']/span[2]</value>
      <webElementGuid>8955f124-4932-48ff-8ce8-509bc85377c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/following::span[2]</value>
      <webElementGuid>05c47846-6dd0-42ab-aed4-5753eef01d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$22,313.27'])[5]/following::span[4]</value>
      <webElementGuid>df7ed0f9-b7a9-4af7-8f31-fe74dac711b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrolment hotline'])[4]/preceding::span[1]</value>
      <webElementGuid>026f4922-8539-4105-953d-274f25b1b80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your subscription and levy (after discounts)'])[4]/preceding::span[1]</value>
      <webElementGuid>ad9b3a08-2cd1-4652-930d-dc5ef13d9656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div[7]/div/div/div/button/span[2]</value>
      <webElementGuid>c2107f61-eeba-48d3-9726-ebd53161f719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>a20167dc-16f3-4234-9982-caeb44ee86cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
