<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get my quote</name>
   <tag></tag>
   <elementGuidId>8eac8f9b-a733-4e46-a40c-b314db46c4b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='get_Quote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#get_Quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77c193ff-0d2e-45d4-af13-bd20af0041ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>get_Quote</value>
      <webElementGuid>a157456d-eb30-424f-8337-47f805a4fc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quote_now_btn</value>
      <webElementGuid>087fc3e6-2fb6-4338-8e92-20b5019e439d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get my quote</value>
      <webElementGuid>05e3ffcb-4a2c-4e95-ad94-2edf98c35fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;get_Quote&quot;)</value>
      <webElementGuid>cdea1a17-b723-41aa-b6e8-ccb885424091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='get_Quote']</value>
      <webElementGuid>a415611e-cde6-4995-9269-d883c2517b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidetextdraw_2087322221__']/div/button</value>
      <webElementGuid>2b4eff12-c349-4bd3-a58d-a4cf282ad63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Online'])[1]/following::button[1]</value>
      <webElementGuid>ce33225e-7d8b-4349-9869-18b041c2d4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify'])[1]/following::button[2]</value>
      <webElementGuid>b7874be5-fe14-4df8-ac12-0299b2f787a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your subscription and levy'])[1]/preceding::button[1]</value>
      <webElementGuid>b7139373-2234-41c6-9c4a-35d346e4e054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$'])[1]/preceding::button[1]</value>
      <webElementGuid>c94d9b5e-5c1e-457c-a5ad-f2c95d35ca4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get my quote']/parent::*</value>
      <webElementGuid>32377898-bd93-4ac4-b557-7da2d8ee3db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button</value>
      <webElementGuid>1ad5d55d-81ab-493d-9abe-3df306c9ecb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'get_Quote' and (text() = 'Get my quote' or . = 'Get my quote')]</value>
      <webElementGuid>1a99d660-3b06-4e4e-bbfb-6db8c74a047a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
