<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Buy Online</name>
   <tag></tag>
   <elementGuidId>db0e1805-c828-4a73-ac2c-1591485c25bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352___widget']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352___widget</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66a5750e-2e1d-46aa-b020-b7e23d9faaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quote_now_btn</value>
      <webElementGuid>9760c9e6-9a5f-4304-9aaa-b4bd934499fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d656e75a-9f55-415e-97e9-f6d4e791d953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352___widget</value>
      <webElementGuid>3ea63aba-7adf-444a-85fd-711ff9a1b61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352___jqName</value>
      <webElementGuid>4411eba9-c5c4-412d-a1bb-4357b0574328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b712176d-b12a-4b08-a293-74758a567e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Buy Online</value>
      <webElementGuid>be52070e-8d6f-40f4-ad63-ad4b6d25ebc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
        Buy Online
    </value>
      <webElementGuid>df7d3c53-784c-4d5c-bae9-c82ef5fd54b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352___widget&quot;)</value>
      <webElementGuid>80f3b352-fbbf-4a95-8414-6816c7bbbd6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352___widget']</value>
      <webElementGuid>7b5ce65a-0f5e-4af4-bced-a69e287a65d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352__']/div/button</value>
      <webElementGuid>2f11b234-c289-4454-920a-a862e744185b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify'])[1]/following::button[1]</value>
      <webElementGuid>b3ec6e5e-b93a-4306-8a03-2ab738f6a1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter your information to get a quote'])[1]/following::button[2]</value>
      <webElementGuid>4aa5b124-60cd-42d0-aef2-e263a1818041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get my quote'])[1]/preceding::button[1]</value>
      <webElementGuid>19fe6667-762b-45d7-b190-870597c2d512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[4]/div/div/div/div/div/div[3]/div/div/div/button</value>
      <webElementGuid>85486cbf-aae5-4b1f-8459-dc13233aacbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352___widget' and @name = 'guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidebutton_2133767352___jqName' and (text() = '
        
        Buy Online
    ' or . = '
        
        Buy Online
    ')]</value>
      <webElementGuid>69827a18-14d6-4929-bf20-0c335ba4f429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
