<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Membership No. of Exisiting Group Mem_29c7a5</name>
   <tag></tag>
   <elementGuidId>bb906e23-3c61-4eaf-9964-9d5bdf621e3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M_MembershipNo_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#M_MembershipNo_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30253902-c417-46c0-b8d7-76099f8252f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ac27d809-dc77-445c-823d-89c4a7be94e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M_MembershipNo_1</value>
      <webElementGuid>69903df3-29b1-4dd5-be5a-3c46050d0937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>bcbd6b42-e99d-47c0-b65c-4b5195a1df48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4f30ad8f-5925-4d8b-8403-61ba937a1007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M_MembershipNo_1&quot;)</value>
      <webElementGuid>aff75ec9-5185-478b-91db-6f13a629d9a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M_MembershipNo_1']</value>
      <webElementGuid>9aca3b43-4aa6-423d-bd7b-ec840607930b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M_MembershipNo']/input</value>
      <webElementGuid>0c78b531-8831-4078-9ebf-cd1b3c136adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>994eeb59-17bc-49a4-b17c-166bfc8061bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'M_MembershipNo_1']</value>
      <webElementGuid>50db3dd0-aa1f-4461-8ee9-22b5a5a3cd02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
