<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__S_Last_Name_Eng</name>
   <tag></tag>
   <elementGuidId>ff12fb3e-ae82-475f-a3f7-82230ecacc76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='S_Last_Name_Eng']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#S_Last_Name_Eng</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29891ed5-bbf3-40c3-9428-d9c5f414f5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa889e14-8831-4fc9-b22e-53a220a46ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>S_Last_Name_Eng</value>
      <webElementGuid>964c0620-2458-4824-a42a-c6572933428b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control check_english</value>
      <webElementGuid>e5253e28-5596-46aa-b4b1-804b5565b4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>2ef55ff4-a8e4-46bd-ac2b-2b1051bb049f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S_Last_Name_Eng&quot;)</value>
      <webElementGuid>0da5aeba-e3e2-4294-8d89-21947485a1e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='S_Last_Name_Eng']</value>
      <webElementGuid>861a54f0-b5dc-4914-90ac-352687843ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Self_Last_Name_Eng']/input</value>
      <webElementGuid>081f5610-cc12-4fc9-8165-b5e4aec05dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>f0f99185-03d9-41df-a993-51eb8da1987c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'S_Last_Name_Eng']</value>
      <webElementGuid>c812da9c-442e-4757-97e3-39703fd700e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
