<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Promotion Code (if any)_Pre_Quote_Discount</name>
   <tag></tag>
   <elementGuidId>dd98ef90-3015-4c53-a52b-c1823cd6f6ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pre_Quote_Discount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pre_Quote_Discount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfb56f19-1d59-4c7a-aec8-bd40dfd375ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11520b9f-2d06-41e0-b815-a63133443d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_dashline</value>
      <webElementGuid>3ee06175-6dca-49cc-8eb0-c36c7eccc341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pre_Quote_Discount</value>
      <webElementGuid>c6d048bf-e6da-47bb-a141-e23410b45acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input here</value>
      <webElementGuid>531738f0-939d-404b-9f13-bef59c2bc787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pre_Quote_Discount&quot;)</value>
      <webElementGuid>9cb15c4b-f4ca-43c8-867a-9ab60b4f62a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pre_Quote_Discount']</value>
      <webElementGuid>037a9e69-0e0b-44b9-845e-cf0a544fbc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Promotion_Offer']/input</value>
      <webElementGuid>ef03bf3a-42a1-46f0-a7b4-ea228b57547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>4b575db8-895b-4fe7-a2db-59cbc6f0d939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Pre_Quote_Discount' and @placeholder = 'Input here']</value>
      <webElementGuid>a68e22a8-fdb3-4333-9ffd-10ee555a1707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
