<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I am a_Pre_Quote_Product_Age</name>
   <tag></tag>
   <elementGuidId>38a187ee-5461-4964-8682-7594720069c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pre_Quote_Product_Age']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pre_Quote_Product_Age</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18d56b1c-cd6c-4fa5-991f-a5ebc744eea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pre_Quote_Product_Age</value>
      <webElementGuid>6c8dc51b-6c5a-46b0-8313-d665a8a625de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_dashline check_number readonly_Age</value>
      <webElementGuid>6c6b3e98-da4a-4d8a-be5c-17d12dccb693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d027c36e-6bb2-4c73-b545-eb5c7b4e6374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>6f18270e-4838-4f0e-83c4-269a723cf493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>69</value>
      <webElementGuid>e2cdeb35-9a66-4679-86bc-8fa2f14619ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>c76ac159-1025-4207-ba20-b909a77deda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pre_Quote_Product_Age&quot;)</value>
      <webElementGuid>99793fba-82e4-4a68-81f8-aa77c08e1534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pre_Quote_Product_Age']</value>
      <webElementGuid>e73f148c-0811-4f71-995e-a4d6054ef412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Pre_Quote_Product_Details_Main']/input</value>
      <webElementGuid>188996b1-6e48-4bdc-b033-ba0c54900f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/div/input</value>
      <webElementGuid>14caeb54-5dc3-4d33-9fcd-4ec890c558bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Pre_Quote_Product_Age' and @type = 'number' and @placeholder = '18']</value>
      <webElementGuid>cb23db04-aacc-468b-ac5c-38ce541b83d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
