<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Area_S_Area</name>
   <tag></tag>
   <elementGuidId>ad408bda-162b-4e8e-8fe4-b2ba15dc9b1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='S_Area']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#S_Area</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d9ec013-ed8a-4bb1-bd12-a26e4fa5ee2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66c2faae-cbe7-4166-a844-2b1ba3dbc1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>S_Area</value>
      <webElementGuid>6012fec7-82e1-46bb-b769-31ac4ef3df65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>70a3a166-2eff-4c52-a44f-c344c86249d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S_Area&quot;)</value>
      <webElementGuid>93cee605-1bc4-4113-b00e-dc8ab8bd4a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='S_Area']</value>
      <webElementGuid>0469f750-8c5e-41a7-a20f-92beec9cbeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Self_Area']/input</value>
      <webElementGuid>96a3ff2a-de32-4582-9ab1-506c7dab0eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/input</value>
      <webElementGuid>d5c8f08d-a7b3-4bf7-a0e6-52d4ecb121e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'S_Area']</value>
      <webElementGuid>4b024824-fa3b-4082-bf4c-b5e4589bad1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
