<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Membership No. of Exisiting Group Member_M_MembershipNo_2</name>
   <tag></tag>
   <elementGuidId>657f241a-48e6-4b24-ba36-8ade5e559685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M_MembershipNo_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#M_MembershipNo_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aa783e0-2b65-40e6-9275-0561bc1e1835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a265054c-79e8-4dd9-bc4b-62a10a0ac161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M_MembershipNo_2</value>
      <webElementGuid>bb46315e-9c3d-4436-9949-868993f046cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>59545adb-ff3e-46be-8263-3642ac79069c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ff897b03-39be-41a4-996f-31833e02202a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M_MembershipNo_2&quot;)</value>
      <webElementGuid>3718346a-4018-44cd-be72-54b3a591eb55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M_MembershipNo_2']</value>
      <webElementGuid>129c68b1-680e-4b4b-9fce-357ff7138891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M_MembershipNo']/input[2]</value>
      <webElementGuid>6228d66d-3015-49b5-91f4-2376e3eb01ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/div/div/input[2]</value>
      <webElementGuid>c320e44c-dd61-4e8f-ba13-069202262cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'M_MembershipNo_2']</value>
      <webElementGuid>cbc51b0b-96b1-4e39-95c3-2fb02124ee69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
