<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Clinical benefit</name>
   <tag></tag>
   <elementGuidId>a8c129f8-a4e6-4369-a585-d79bd315fdfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Self_Clinical']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Self_Clinical > label.label_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2f0d29dc-9d62-49f0-a7ff-6feb8e03709b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_en</value>
      <webElementGuid>ec91d99e-eb81-44c2-8e97-83f182f144b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CB_Self_Clinical</value>
      <webElementGuid>c3acd7d1-cf7e-426f-ac8d-80fdf3f5a0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clinical benefit 
</value>
      <webElementGuid>db179684-5d50-440a-957f-3498cddcb9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Self_Clinical&quot;)/label[@class=&quot;label_en&quot;]</value>
      <webElementGuid>9825e8f9-3991-48e1-8708-e69e6c04ffb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Self_Clinical']/label</value>
      <webElementGuid>c692835e-8d85-4749-a227-52f2a41ec621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add other optional benefit(s)'])[1]/following::label[2]</value>
      <webElementGuid>ca9ac845-943b-4b7c-bd22-0d3e0e2edd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lump Sum Hospital &amp; Surgical Benefit'])[1]/following::label[2]</value>
      <webElementGuid>7cd27c21-ff51-4a25-91b6-14ef575b6786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My'])[1]/preceding::label[1]</value>
      <webElementGuid>97336360-c578-49d7-9953-0723b1c3f6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/label</value>
      <webElementGuid>8dd33163-a7bb-4bb1-ad29-964c1b3e07c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Clinical benefit 
' or . = 'Clinical benefit 
')]</value>
      <webElementGuid>1b37c91b-c856-4708-819f-f454e10c277f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
