<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Semi-Private</name>
   <tag></tag>
   <elementGuidId>56694e5d-3e06-4fc2-942e-6b7f060545c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='Label_Semi_Private']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Label_Semi_Private</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7378c1cf-a514-49bc-b96d-f69253445c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_en</value>
      <webElementGuid>a73a9ce5-a319-44ba-bdc4-8554013e00e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Guarantee_Level_Semi_Private</value>
      <webElementGuid>d0059661-d38e-4c32-bff5-2030030b5797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Label_Semi_Private</value>
      <webElementGuid>a1d7c444-e930-48c3-af3a-f97c0c9cdf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semi-Private</value>
      <webElementGuid>fb8e8b3a-ee75-49a3-b8f5-7f893c0aaa50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Label_Semi_Private&quot;)</value>
      <webElementGuid>b229484a-9da9-4ec7-9db0-596e3bee1245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='Label_Semi_Private']</value>
      <webElementGuid>5d6bd1ba-8a12-435b-a0c9-12ba6f24402a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='Pre_Quote_Select_Option']/label)[4]</value>
      <webElementGuid>61ff43bc-41f5-412b-ae64-9fed2c2b3a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::label[1]</value>
      <webElementGuid>cd491d12-2445-45b2-be7b-0a7f43246766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefit level'])[1]/following::label[2]</value>
      <webElementGuid>b2fcd4a6-a27b-4e96-b614-a49ab5ea5fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ward'])[1]/preceding::label[1]</value>
      <webElementGuid>9ef94378-151b-44be-9329-14a227da93d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label</value>
      <webElementGuid>2636d36b-2ae3-4511-91c1-2e0526dce719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'Label_Semi_Private' and (text() = 'Semi-Private' or . = 'Semi-Private')]</value>
      <webElementGuid>1e37a2f2-ad49-4b91-bc19-409f2249cae6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
