<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Gender Male Female</name>
   <tag></tag>
   <elementGuidId>bab279c3-a38b-4a19-8c75-d57e6a434ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Pre_Quote_Product_Genders']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pre_Quote_Product_Genders</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c921e024-3957-4b73-adb6-02fe6470e39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pre_Quote_Product_Gender</value>
      <webElementGuid>d7b08189-c5a2-4b7a-ba7c-7035996fac6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pre_Quote_Product_Genders</value>
      <webElementGuid>f6a5f631-0a41-4e8b-8898-773fed85f246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_dashline</value>
      <webElementGuid>7258ea76-00de-4bc4-af11-cef17b5bb719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gender Male Female</value>
      <webElementGuid>c94cf0fc-d240-4f9b-867c-b4d4393d613d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pre_Quote_Product_Genders&quot;)</value>
      <webElementGuid>803a9d74-1fe4-450f-bf0f-4c27ab460ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Pre_Quote_Product_Genders']</value>
      <webElementGuid>77afc915-49ce-49c7-a07c-37dedeb6e683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Pre_Quote_Product_Details_Main']/select</value>
      <webElementGuid>5eb6a243-0631-4af4-938c-50309045a0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='year old'])[1]/following::select[1]</value>
      <webElementGuid>df7b2350-5d74-48f9-8cc4-3112ea9a1ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am a'])[1]/following::select[1]</value>
      <webElementGuid>5acae052-c83a-4d80-a1c5-a29ba288d7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(As a policy holder, you must be aged 18 or above. You can add other family members later.)'])[1]/preceding::select[1]</value>
      <webElementGuid>d3367034-09e3-4743-8715-4285d2584654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter the age between 18 to 69'])[1]/preceding::select[1]</value>
      <webElementGuid>f55ea4a1-4763-40d1-b7ed-798e3616f77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>1512b740-c36d-470c-b07a-be969e79b9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Pre_Quote_Product_Gender' and @id = 'Pre_Quote_Product_Genders' and (text() = 'Gender Male Female' or . = 'Gender Male Female')]</value>
      <webElementGuid>d5078634-326b-4522-950f-9f11a3a16f22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
