<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select Terminated</name>
   <tag></tag>
   <elementGuidId>6b6bb33a-f75f-47e9-8d5b-74bbaecaf388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='S_Eligibilitys']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#S_Eligibilitys</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e50d856-d9e7-4ca9-aae4-8bf3b3cb31b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>S_Eligibility</value>
      <webElementGuid>545c539d-0088-45a1-915d-b83c37f39117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>S_Eligibilitys</value>
      <webElementGuid>096bc6a1-3d0d-4dd4-a810-a62dd39df99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>11fb3f9a-cf3c-47ab-b6d6-8978c8c6fbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Please Select Terminated employment Newly covered under Bupa group scheme Bupa group scheme is renewed within 60 days Retired Newly married or has a new born child Reaching age 70</value>
      <webElementGuid>7875b959-e5be-43d3-8be6-ad1f86cafa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S_Eligibilitys&quot;)</value>
      <webElementGuid>6df78521-214c-4bc9-bc4b-9cfe86eaea77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='S_Eligibilitys']</value>
      <webElementGuid>0e2fdc3b-d64d-4d49-88be-47f84c1f87cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Self_Eligibility']/select</value>
      <webElementGuid>4f036914-d312-4495-9183-a61cf212ecd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>59e99bc7-fbf1-4d8c-99d8-8eb8d993c03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Date of Birth doesn', &quot;'&quot;, 't match with the current group membership record')])[1]/following::select[1]</value>
      <webElementGuid>25288751-663e-43e9-beec-90f184083388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Last date of Bupa Group Health Insurance Scheme', &quot;'&quot;, 's Membership')])[1]/preceding::select[1]</value>
      <webElementGuid>390925ea-ff5c-4c8c-b541-48ccc26dfa58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>f11c7af2-1d8b-405a-a5d1-f2337962bcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'S_Eligibility' and @id = 'S_Eligibilitys' and (text() = ' Please Select Terminated employment Newly covered under Bupa group scheme Bupa group scheme is renewed within 60 days Retired Newly married or has a new born child Reaching age 70' or . = ' Please Select Terminated employment Newly covered under Bupa group scheme Bupa group scheme is renewed within 60 days Retired Newly married or has a new born child Reaching age 70')]</value>
      <webElementGuid>ebd8155a-e571-436e-bfbe-6c4129ccda5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
