<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select003 - Standard Chartered Bank</name>
   <tag></tag>
   <elementGuidId>aff5488e-a3ec-4c6e-aa16-c2e011162f43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='S_Bankname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#S_Bankname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>04ddc587-3aa1-4098-b47b-42045194fcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>S_Bankname</value>
      <webElementGuid>a4232435-375a-4dfb-b9a9-711df27b6732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>S_Bankname</value>
      <webElementGuid>49b40ec0-28d5-4653-b908-7e8d3ab234d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b68f035e-7274-4520-88c1-861f217fdc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Please Select003 - Standard Chartered Bank (Hong Kong) Limited004 - Hongkong and Shanghai Banking Corporation005 - Credit Agricole Corporate And Investment Bank006 - Citibank N.A.007 - Jpmorgan Chase Bank, N.A., Hong Kong008 - The Royal Bank Of Scotland Plc009 - China Construction Bank (Asia)012 - Bank Of China (Hong Kong) Limited015 - The Bank of East Asia, Limited016 - DBS Bank (Hong Kong)018 - China CITIC Bank International020 - Wing Lung Bank022 - Oversea-Chinese Banking Corporation Ltd024 - Hang Seng Bank025 - Shanghai Commercial Bank027 - Bank Of Communications Co., Ltd.028 - Public Bank (Hong Kong)035 - OCBC Wing Hang Bank038 - Tai Yau Bank039 - Chiyu Banking Corporation040 - Dah Sing Bank041 - Chong Hing Bank043 - Nanyang Commercial Bank045 - Uco Bank046 - Korea Exchange Bank047 - The Bank Of Tokyo-Mitsubishi Ufj, Ltd.049 - Bangkok Bank Public Company Ltd050 - Indian Overseas Bank054 - Deutsche Bank Ag055 - Bank Of America, National Association056 - Bnp Paribas058 - Bank Of India060 - National Bank Of Pakistan061 - Dah Sing Bank Limited063 - Maybank (Malayan Banking Berhad)065 - Sumitomo Mitsui Banking Corporation066 - Pt. Bank Negara Indonesia (Persero) Tbk.067 - Banco De Oro Unibank, Inc.071 - United Overseas Bank Ltd072 - Industrial and Commercial Bank of China (Asia)074 - Barclays Bank Plc076 - The Bank Of Nova Scotia080 - Royal Bank Of Canada081 - Societe Generale082 - State Bank Of India085 - The Toronto-Dominion Bank086 - Bank Of Montreal092 - Canadian Imperial Bank Of Commerce097 - Commerzbank Ag103 - Ubs Ag, Hong Kong106 - Hsbc Bank Usa, National Association109 - Mizuho Bank, Ltd.112 - Hana Bank113 - DZ Bank Ag Deutsche Zentral-Genossenschaftsbank118 - Woori Bank119 - Philippine National Bank128 - Fubon Bank (Hong Kong)138 - Mitsubishi Ufj Trust And Banking Corporation139 - The Bank Of New York Mellon145 - ING Bank N.V.147 - Banco Bilbao Vizcaya Argentaria, S.A.150 - National Australia Bank Ltd151 - Westpac Banking Corporation152 - Australia And New Zealand Banking Group Ltd153 - Commonwealth Bank Of Australia161 - Intesa Sanpaolo S.p.A.164 - Unicredit Bank Ag165 - Svenska Handelsbanken Ab (Publ)170 - The Chiba Bank Ltd178 - KBC Bank N.V.180 - Wells Fargo Bank, N.A.183 - Cooperatieve Centrale Raiffeisen-Boerenleenbank B.A.185 - Dbs Bank Ltd, Hong Kong Branch186 - The Shizuoka Bank, Ltd188 - The Hachijuni Bank, Ltd198 - Hua Nan Commercial Bank Ltd199 - The Shiga Bank, Ltd.201 - Bank Of Taiwan202 - The Chugoku Bank Ltd203 - First Commercial Bank205 - Coutts &amp; Co Ltd206 - Chang Hwa Commercial Bank Ltd210 - Natixis214 - Industrial And Commercial Bank Of China Limited218 - Portigon AG220 - State Street Bank And Trust Company221 - China Construction Bank Corporation222 - Agricultural Bank Of China Limited224 - The Iyo Bank Ltd227 - Erste Group Bank AG229 - Ctbc Bank Co., Ltd.230 - Taiwan Business Bank Hong Kong Branch233 - Credit Suisse AG234 - Banca Monte Dei Paschi Di Siena S.P.A.-Hong Kong Branch235 - Hsbc Private Bank (Suisse) Sa236 - Cathay United Bank Company, Limited237 - Efg Bank Ag238 - China Merchants Bank Co., Ltd.239 - Taipei Fubon Commercial Bank Co., Ltd.240 - Bnp Paribas Wealth Management241 - Bank Sinopac242 - Mega International Commercial Bank Co., Ltd.243 - E.Sun Commercial Bank, Ltd245 - Taishin International Bank Co., Ltd248 - Hong Leong Bank Berhad249 - Standard Chartered Bank Hong Kong Branch250 - Citibank (Hong Kong)251 - Icici Bank Limited253 - Falcon Private Bank Ltd.254 - Melli Bank Plc255 - Societe Generale Bank &amp; Trust256 - Allahabad Bank257 - Newedge Group258 - East West Bank259 - Bank Of Baroda260 - Far Eastern International Bank261 - Axis Bank Limited262 - Canara Bank263 - Cathay Bank264 - Land Bank Of Taiwan Co., Ltd.265 - Taiwan Cooperative Bank, Ltd.266 - Punjab National Bank267 - Banco Santander, S.A.268 - Union Bank Of India269 - The Shanghai Commercial &amp; Savings Bank Ltd271 - Industrial Bank Of Korea272 - Bank Of Singapore Limited273 - Shinhan Bank274 - Industrial Bank Of Taiwan Co., Ltd.275 - Bnp Paribas Securities Services276 - China Development Bank Corporation277 - National Bank Of Abu Dhabi278 - Bank J. Safra Sarasin Ltd307 - ABN AMRO Bank N.V.308 - HDFC Bank Ltd.313 - Lloyds Tsb Bank Plc316 - Skandinaviska Enskilda Banken AB320 - Bank Julius Baer &amp; Co. Ltd.337 - Taiwan Shin Kong Commercial Bank Co., Ltd.338 - Bank Of China Limited, Hong Kong Branch339 - Credit Agricole (Suisse) S.A.341 - Standard Bank Plc342 - Lgt Bank AG344 - Macquarie Bank Limited345 - Shanghai Pudong Development Bank Co., Ltd346 - Banque Privee Edmond De Rothschild Sa350 - BSI Ltd353 - China Minsheng Banking Corp., Ltd.357 - Pictet &amp; Cie (Europe) S.A.360 - The Royal Bank Of Scotland N.V.368 - China Everbright Bank Co., Ltd370 - Raiffeisen Bank International AG371 - Sumitomo Mitsui Trust Bank, Limited382 - Bank of Communications Co., Ltd868 - Continuous Linked Settlement Bank International</value>
      <webElementGuid>d4316096-a2a6-40d2-b952-fe43620c3326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S_Bankname&quot;)</value>
      <webElementGuid>229df951-3ae5-467b-bd0f-e201b8a46139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='S_Bankname']</value>
      <webElementGuid>e00c524b-f583-4941-925b-b260bb88ce00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Self_Bankname']/select</value>
      <webElementGuid>29d684dc-ae67-4a29-9218-f3073bed5496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank name'])[1]/following::select[1]</value>
      <webElementGuid>b0b1c8e7-f0aa-4ae2-890a-ba0039c3bce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Account Holder', &quot;'&quot;, 's Name')])[2]/following::select[1]</value>
      <webElementGuid>a14a2267-f49b-4503-8531-22b68595e2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select your bank'])[1]/preceding::select[1]</value>
      <webElementGuid>07fbd4bf-6aa8-4a79-b432-a1b41611e810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account No.'])[1]/preceding::select[1]</value>
      <webElementGuid>91c40964-844b-4c70-8017-cb6c210d5ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/select</value>
      <webElementGuid>813070ce-4156-4d1d-8ce9-64b1268cfbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'S_Bankname' and @id = 'S_Bankname' and (text() = ' Please Select003 - Standard Chartered Bank (Hong Kong) Limited004 - Hongkong and Shanghai Banking Corporation005 - Credit Agricole Corporate And Investment Bank006 - Citibank N.A.007 - Jpmorgan Chase Bank, N.A., Hong Kong008 - The Royal Bank Of Scotland Plc009 - China Construction Bank (Asia)012 - Bank Of China (Hong Kong) Limited015 - The Bank of East Asia, Limited016 - DBS Bank (Hong Kong)018 - China CITIC Bank International020 - Wing Lung Bank022 - Oversea-Chinese Banking Corporation Ltd024 - Hang Seng Bank025 - Shanghai Commercial Bank027 - Bank Of Communications Co., Ltd.028 - Public Bank (Hong Kong)035 - OCBC Wing Hang Bank038 - Tai Yau Bank039 - Chiyu Banking Corporation040 - Dah Sing Bank041 - Chong Hing Bank043 - Nanyang Commercial Bank045 - Uco Bank046 - Korea Exchange Bank047 - The Bank Of Tokyo-Mitsubishi Ufj, Ltd.049 - Bangkok Bank Public Company Ltd050 - Indian Overseas Bank054 - Deutsche Bank Ag055 - Bank Of America, National Association056 - Bnp Paribas058 - Bank Of India060 - National Bank Of Pakistan061 - Dah Sing Bank Limited063 - Maybank (Malayan Banking Berhad)065 - Sumitomo Mitsui Banking Corporation066 - Pt. Bank Negara Indonesia (Persero) Tbk.067 - Banco De Oro Unibank, Inc.071 - United Overseas Bank Ltd072 - Industrial and Commercial Bank of China (Asia)074 - Barclays Bank Plc076 - The Bank Of Nova Scotia080 - Royal Bank Of Canada081 - Societe Generale082 - State Bank Of India085 - The Toronto-Dominion Bank086 - Bank Of Montreal092 - Canadian Imperial Bank Of Commerce097 - Commerzbank Ag103 - Ubs Ag, Hong Kong106 - Hsbc Bank Usa, National Association109 - Mizuho Bank, Ltd.112 - Hana Bank113 - DZ Bank Ag Deutsche Zentral-Genossenschaftsbank118 - Woori Bank119 - Philippine National Bank128 - Fubon Bank (Hong Kong)138 - Mitsubishi Ufj Trust And Banking Corporation139 - The Bank Of New York Mellon145 - ING Bank N.V.147 - Banco Bilbao Vizcaya Argentaria, S.A.150 - National Australia Bank Ltd151 - Westpac Banking Corporation152 - Australia And New Zealand Banking Group Ltd153 - Commonwealth Bank Of Australia161 - Intesa Sanpaolo S.p.A.164 - Unicredit Bank Ag165 - Svenska Handelsbanken Ab (Publ)170 - The Chiba Bank Ltd178 - KBC Bank N.V.180 - Wells Fargo Bank, N.A.183 - Cooperatieve Centrale Raiffeisen-Boerenleenbank B.A.185 - Dbs Bank Ltd, Hong Kong Branch186 - The Shizuoka Bank, Ltd188 - The Hachijuni Bank, Ltd198 - Hua Nan Commercial Bank Ltd199 - The Shiga Bank, Ltd.201 - Bank Of Taiwan202 - The Chugoku Bank Ltd203 - First Commercial Bank205 - Coutts &amp; Co Ltd206 - Chang Hwa Commercial Bank Ltd210 - Natixis214 - Industrial And Commercial Bank Of China Limited218 - Portigon AG220 - State Street Bank And Trust Company221 - China Construction Bank Corporation222 - Agricultural Bank Of China Limited224 - The Iyo Bank Ltd227 - Erste Group Bank AG229 - Ctbc Bank Co., Ltd.230 - Taiwan Business Bank Hong Kong Branch233 - Credit Suisse AG234 - Banca Monte Dei Paschi Di Siena S.P.A.-Hong Kong Branch235 - Hsbc Private Bank (Suisse) Sa236 - Cathay United Bank Company, Limited237 - Efg Bank Ag238 - China Merchants Bank Co., Ltd.239 - Taipei Fubon Commercial Bank Co., Ltd.240 - Bnp Paribas Wealth Management241 - Bank Sinopac242 - Mega International Commercial Bank Co., Ltd.243 - E.Sun Commercial Bank, Ltd245 - Taishin International Bank Co., Ltd248 - Hong Leong Bank Berhad249 - Standard Chartered Bank Hong Kong Branch250 - Citibank (Hong Kong)251 - Icici Bank Limited253 - Falcon Private Bank Ltd.254 - Melli Bank Plc255 - Societe Generale Bank &amp; Trust256 - Allahabad Bank257 - Newedge Group258 - East West Bank259 - Bank Of Baroda260 - Far Eastern International Bank261 - Axis Bank Limited262 - Canara Bank263 - Cathay Bank264 - Land Bank Of Taiwan Co., Ltd.265 - Taiwan Cooperative Bank, Ltd.266 - Punjab National Bank267 - Banco Santander, S.A.268 - Union Bank Of India269 - The Shanghai Commercial &amp; Savings Bank Ltd271 - Industrial Bank Of Korea272 - Bank Of Singapore Limited273 - Shinhan Bank274 - Industrial Bank Of Taiwan Co., Ltd.275 - Bnp Paribas Securities Services276 - China Development Bank Corporation277 - National Bank Of Abu Dhabi278 - Bank J. Safra Sarasin Ltd307 - ABN AMRO Bank N.V.308 - HDFC Bank Ltd.313 - Lloyds Tsb Bank Plc316 - Skandinaviska Enskilda Banken AB320 - Bank Julius Baer &amp; Co. Ltd.337 - Taiwan Shin Kong Commercial Bank Co., Ltd.338 - Bank Of China Limited, Hong Kong Branch339 - Credit Agricole (Suisse) S.A.341 - Standard Bank Plc342 - Lgt Bank AG344 - Macquarie Bank Limited345 - Shanghai Pudong Development Bank Co., Ltd346 - Banque Privee Edmond De Rothschild Sa350 - BSI Ltd353 - China Minsheng Banking Corp., Ltd.357 - Pictet &amp; Cie (Europe) S.A.360 - The Royal Bank Of Scotland N.V.368 - China Everbright Bank Co., Ltd370 - Raiffeisen Bank International AG371 - Sumitomo Mitsui Trust Bank, Limited382 - Bank of Communications Co., Ltd868 - Continuous Linked Settlement Bank International' or . = ' Please Select003 - Standard Chartered Bank (Hong Kong) Limited004 - Hongkong and Shanghai Banking Corporation005 - Credit Agricole Corporate And Investment Bank006 - Citibank N.A.007 - Jpmorgan Chase Bank, N.A., Hong Kong008 - The Royal Bank Of Scotland Plc009 - China Construction Bank (Asia)012 - Bank Of China (Hong Kong) Limited015 - The Bank of East Asia, Limited016 - DBS Bank (Hong Kong)018 - China CITIC Bank International020 - Wing Lung Bank022 - Oversea-Chinese Banking Corporation Ltd024 - Hang Seng Bank025 - Shanghai Commercial Bank027 - Bank Of Communications Co., Ltd.028 - Public Bank (Hong Kong)035 - OCBC Wing Hang Bank038 - Tai Yau Bank039 - Chiyu Banking Corporation040 - Dah Sing Bank041 - Chong Hing Bank043 - Nanyang Commercial Bank045 - Uco Bank046 - Korea Exchange Bank047 - The Bank Of Tokyo-Mitsubishi Ufj, Ltd.049 - Bangkok Bank Public Company Ltd050 - Indian Overseas Bank054 - Deutsche Bank Ag055 - Bank Of America, National Association056 - Bnp Paribas058 - Bank Of India060 - National Bank Of Pakistan061 - Dah Sing Bank Limited063 - Maybank (Malayan Banking Berhad)065 - Sumitomo Mitsui Banking Corporation066 - Pt. Bank Negara Indonesia (Persero) Tbk.067 - Banco De Oro Unibank, Inc.071 - United Overseas Bank Ltd072 - Industrial and Commercial Bank of China (Asia)074 - Barclays Bank Plc076 - The Bank Of Nova Scotia080 - Royal Bank Of Canada081 - Societe Generale082 - State Bank Of India085 - The Toronto-Dominion Bank086 - Bank Of Montreal092 - Canadian Imperial Bank Of Commerce097 - Commerzbank Ag103 - Ubs Ag, Hong Kong106 - Hsbc Bank Usa, National Association109 - Mizuho Bank, Ltd.112 - Hana Bank113 - DZ Bank Ag Deutsche Zentral-Genossenschaftsbank118 - Woori Bank119 - Philippine National Bank128 - Fubon Bank (Hong Kong)138 - Mitsubishi Ufj Trust And Banking Corporation139 - The Bank Of New York Mellon145 - ING Bank N.V.147 - Banco Bilbao Vizcaya Argentaria, S.A.150 - National Australia Bank Ltd151 - Westpac Banking Corporation152 - Australia And New Zealand Banking Group Ltd153 - Commonwealth Bank Of Australia161 - Intesa Sanpaolo S.p.A.164 - Unicredit Bank Ag165 - Svenska Handelsbanken Ab (Publ)170 - The Chiba Bank Ltd178 - KBC Bank N.V.180 - Wells Fargo Bank, N.A.183 - Cooperatieve Centrale Raiffeisen-Boerenleenbank B.A.185 - Dbs Bank Ltd, Hong Kong Branch186 - The Shizuoka Bank, Ltd188 - The Hachijuni Bank, Ltd198 - Hua Nan Commercial Bank Ltd199 - The Shiga Bank, Ltd.201 - Bank Of Taiwan202 - The Chugoku Bank Ltd203 - First Commercial Bank205 - Coutts &amp; Co Ltd206 - Chang Hwa Commercial Bank Ltd210 - Natixis214 - Industrial And Commercial Bank Of China Limited218 - Portigon AG220 - State Street Bank And Trust Company221 - China Construction Bank Corporation222 - Agricultural Bank Of China Limited224 - The Iyo Bank Ltd227 - Erste Group Bank AG229 - Ctbc Bank Co., Ltd.230 - Taiwan Business Bank Hong Kong Branch233 - Credit Suisse AG234 - Banca Monte Dei Paschi Di Siena S.P.A.-Hong Kong Branch235 - Hsbc Private Bank (Suisse) Sa236 - Cathay United Bank Company, Limited237 - Efg Bank Ag238 - China Merchants Bank Co., Ltd.239 - Taipei Fubon Commercial Bank Co., Ltd.240 - Bnp Paribas Wealth Management241 - Bank Sinopac242 - Mega International Commercial Bank Co., Ltd.243 - E.Sun Commercial Bank, Ltd245 - Taishin International Bank Co., Ltd248 - Hong Leong Bank Berhad249 - Standard Chartered Bank Hong Kong Branch250 - Citibank (Hong Kong)251 - Icici Bank Limited253 - Falcon Private Bank Ltd.254 - Melli Bank Plc255 - Societe Generale Bank &amp; Trust256 - Allahabad Bank257 - Newedge Group258 - East West Bank259 - Bank Of Baroda260 - Far Eastern International Bank261 - Axis Bank Limited262 - Canara Bank263 - Cathay Bank264 - Land Bank Of Taiwan Co., Ltd.265 - Taiwan Cooperative Bank, Ltd.266 - Punjab National Bank267 - Banco Santander, S.A.268 - Union Bank Of India269 - The Shanghai Commercial &amp; Savings Bank Ltd271 - Industrial Bank Of Korea272 - Bank Of Singapore Limited273 - Shinhan Bank274 - Industrial Bank Of Taiwan Co., Ltd.275 - Bnp Paribas Securities Services276 - China Development Bank Corporation277 - National Bank Of Abu Dhabi278 - Bank J. Safra Sarasin Ltd307 - ABN AMRO Bank N.V.308 - HDFC Bank Ltd.313 - Lloyds Tsb Bank Plc316 - Skandinaviska Enskilda Banken AB320 - Bank Julius Baer &amp; Co. Ltd.337 - Taiwan Shin Kong Commercial Bank Co., Ltd.338 - Bank Of China Limited, Hong Kong Branch339 - Credit Agricole (Suisse) S.A.341 - Standard Bank Plc342 - Lgt Bank AG344 - Macquarie Bank Limited345 - Shanghai Pudong Development Bank Co., Ltd346 - Banque Privee Edmond De Rothschild Sa350 - BSI Ltd353 - China Minsheng Banking Corp., Ltd.357 - Pictet &amp; Cie (Europe) S.A.360 - The Royal Bank Of Scotland N.V.368 - China Everbright Bank Co., Ltd370 - Raiffeisen Bank International AG371 - Sumitomo Mitsui Trust Bank, Limited382 - Bank of Communications Co., Ltd868 - Continuous Linked Settlement Bank International')]</value>
      <webElementGuid>885329d5-4ebb-452c-99b8-a3dec097e7bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
