<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HK22,313.27</name>
   <tag></tag>
   <elementGuidId>59605514-5826-4b23-a27e-9a791bf40793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>get</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#total_pre_quote_price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c2bd0f9a-2753-4623-a9fa-bba2bc9643d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total_pre_quote_price</value>
      <webElementGuid>ff4749e4-69df-4368-b0d0-78ddd6a9e1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HK$22,313.27</value>
      <webElementGuid>876dd054-783d-4743-ab48-33e5964a0b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total_pre_quote_price&quot;)</value>
      <webElementGuid>d992106e-7519-4ba0-880a-fc71a0e71d03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='total_pre_quote_price']</value>
      <webElementGuid>56b966a3-0e5a-4010-ad86-7f7801e2e370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Pre_Quote_Count']/div/span</value>
      <webElementGuid>353e1425-9ebc-4ead-b7ef-efb5aec5a382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$'])[2]/following::span[1]</value>
      <webElementGuid>e5f46df8-e969-47cf-9c2c-44ef51ed8144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount'])[1]/following::span[1]</value>
      <webElementGuid>681c56d2-13bc-4da3-99d7-4724a84970e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your total'])[1]/preceding::span[1]</value>
      <webElementGuid>134c7ab9-6e5d-4fa2-a15b-96f874d2f625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$24,765.00'])[1]/preceding::span[1]</value>
      <webElementGuid>2632aa37-9080-436a-965a-b01e986888bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HK$22,313.27']/parent::*</value>
      <webElementGuid>b653d55d-4bfb-4a7b-ba1d-299d76f27cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[3]/div/span</value>
      <webElementGuid>6f274c2a-7791-489c-ad32-d14e3cb9ed6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'total_pre_quote_price' and (text() = 'HK$22,313.27' or . = 'HK$22,313.27')]</value>
      <webElementGuid>3430065a-d92d-48bf-a1a3-7465b4a7e2f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
