<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_APP-00005130-P3L5Q2</name>
   <tag></tag>
   <elementGuidId>7bea8558-6401-465b-9e38-6a14f3f93ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Pre_Quote_Count']/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'P_Application_No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P_Application_No</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d98b1ff0-9f47-4c46-be7b-0d3e55d5bb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P_Application_No</value>
      <webElementGuid>50f44f12-d45e-489c-85fa-67455a420ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>APP-00005130-P3L5Q2</value>
      <webElementGuid>b3c70446-efce-477b-8996-9ec6df55c95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P_Application_No&quot;)</value>
      <webElementGuid>7dfdca2a-02f9-49d6-97ff-5b863f641f3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='P_Application_No']</value>
      <webElementGuid>ebb87769-d732-4f2b-bac3-ae7f75c7786d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guideContainer-rootPanel-panel_322752692-panel_1962276397-guidetextdraw__']/p/span[2]</value>
      <webElementGuid>49779a5a-74ac-4bcc-aed5-6f607d214df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application No.:'])[3]/following::span[1]</value>
      <webElementGuid>7d6aaaba-153e-4f8c-906f-94a9b4c5f620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let us call you'])[3]/following::span[2]</value>
      <webElementGuid>ce8ee3a6-88f2-4ceb-b590-bd5b30c82021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Quotation'])[1]/preceding::span[1]</value>
      <webElementGuid>250954a0-e630-4d00-9d25-7565759af127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='for Bupa VTop Health Insurance Scheme - Eligibility'])[1]/preceding::span[1]</value>
      <webElementGuid>b3d5d2e6-f13d-4d6d-9c45-5b5a67aadeac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span[2]</value>
      <webElementGuid>e7959016-330d-4fda-8917-8e3c2ff0d350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'P_Application_No' and (text() = 'APP-00005130-P3L5Q2' or . = 'APP-00005130-P3L5Q2')]</value>
      <webElementGuid>c70b6e9a-02d4-4751-94b7-0584dddca210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
