<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get my quote</name>
   <tag></tag>
   <elementGuidId>f9af07b0-22e3-4a18-ab6f-eb322b8be1bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='get_Quote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#get_Quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7969c2f9-72e9-44fe-86d7-986f8922332d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>get_Quote</value>
      <webElementGuid>203210f5-4ccf-40d5-b71d-585015feb91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quote_now_btn</value>
      <webElementGuid>b898546c-f408-4860-b22d-403cff532fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get my quote</value>
      <webElementGuid>9939f5d6-9141-4992-83c9-d6ff8ae20159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;get_Quote&quot;)</value>
      <webElementGuid>8fc792e6-79e4-4f01-b849-1da1a5d5822a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='get_Quote']</value>
      <webElementGuid>ea984a2e-92b3-4f2f-a75e-d4716d06935b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidetextdraw_2087322221__']/div/button</value>
      <webElementGuid>0fb3f746-a514-4682-91eb-d3275e5f5576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Online'])[1]/following::button[1]</value>
      <webElementGuid>4662be4a-31a0-4386-84fa-29b092d0315a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify'])[1]/following::button[2]</value>
      <webElementGuid>b20f7f01-8123-423d-9ad8-c642f94a9e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your subscription and levy'])[1]/preceding::button[1]</value>
      <webElementGuid>32ce3856-7dc1-415a-97b4-40c24c1ff517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$'])[1]/preceding::button[1]</value>
      <webElementGuid>7acd8ce1-54af-4c59-bd17-b0cb148708b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get my quote']/parent::*</value>
      <webElementGuid>e8c8a6e2-9bd5-4438-b2a8-8cc39bce888d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button</value>
      <webElementGuid>6ea9a955-2e42-4db7-b234-c3aa535fb731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'get_Quote' and (text() = 'Get my quote' or . = 'Get my quote')]</value>
      <webElementGuid>3e1b1ab8-afdd-49d0-b6a9-8da750938e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
