<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I am a_Pre_Quote_Product_Age</name>
   <tag></tag>
   <elementGuidId>47c7703b-4740-4a3b-a756-8fa6e940af55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pre_Quote_Product_Age']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pre_Quote_Product_Age</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a79769d-b46c-452f-91db-28b97880210f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pre_Quote_Product_Age</value>
      <webElementGuid>c41824a8-3576-4ca6-b42f-80ea257896d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_dashline check_number readonly_Age</value>
      <webElementGuid>ccc9899e-5847-4d18-a73c-992bdaba5bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c42c6c6d-e0e8-4bcc-9bb7-dac3800a7d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>9aa7d508-43df-4c02-82db-3ca217f6e70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>69</value>
      <webElementGuid>00106ec8-3d26-42fb-8316-81e0bd760b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>06805290-0254-423f-b774-81cb4293837e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pre_Quote_Product_Age&quot;)</value>
      <webElementGuid>e557fb35-5bc0-4465-a9cc-8a501c82c6fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pre_Quote_Product_Age']</value>
      <webElementGuid>4ff9751e-a974-48cd-a3b1-2d1860edee00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Pre_Quote_Product_Details_Main']/input</value>
      <webElementGuid>e327e48b-e4ae-4441-8851-9ced49ae2e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/div/input</value>
      <webElementGuid>4c66e866-763e-4ab0-9214-6de96845310d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Pre_Quote_Product_Age' and @type = 'number' and @placeholder = '18']</value>
      <webElementGuid>b3ba8c72-5be8-452a-a49d-51c1d81d6839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
