<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Membership No. of Exisiting Group Member_M_MembershipNo_2</name>
   <tag></tag>
   <elementGuidId>6a31e4ba-45df-43b7-8a78-11fe321c7274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M_MembershipNo_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#M_MembershipNo_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3239e89e-9514-4f16-b630-a111a995a492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>616d4412-816e-47e4-9c58-5d614f26c922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M_MembershipNo_2</value>
      <webElementGuid>25e73b29-750f-43c8-a51f-2ffa868be3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>424fcb4c-dffe-4b5d-999d-40a5bfa433f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f4098942-6688-49f0-9412-4c51ad5d549d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M_MembershipNo_2&quot;)</value>
      <webElementGuid>51aeab67-dd87-491f-91e1-b91059825687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M_MembershipNo_2']</value>
      <webElementGuid>b23ad47a-40d5-48e4-8cf0-359f15487cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M_MembershipNo']/input[2]</value>
      <webElementGuid>5092d6de-82fa-44ce-b879-cc189639392e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div/input[2]</value>
      <webElementGuid>d7e9a975-9c9c-43d7-81df-2192feb9d4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'M_MembershipNo_2']</value>
      <webElementGuid>494a4ee9-8c2d-46ab-a5b0-de20332d336e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
