<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Semi-Private</name>
   <tag></tag>
   <elementGuidId>e501d782-38e2-4c34-9774-178f388c6dba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='Label_Semi_Private']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Label_Semi_Private</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c3d3a018-270a-4c50-a959-4921fe2e1600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_en</value>
      <webElementGuid>92c9b819-b716-4e62-b0ba-05b0d5c3b6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Guarantee_Level_Semi_Private</value>
      <webElementGuid>2ec33c82-a9c5-4936-a6e4-7220935803fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Label_Semi_Private</value>
      <webElementGuid>2bfffd6b-affc-410f-8b37-bde13f293d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semi-Private</value>
      <webElementGuid>05d0c2e0-f207-4889-b5ec-f8f078c53e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Label_Semi_Private&quot;)</value>
      <webElementGuid>2059c2b0-878d-4abd-9fec-a551c027f201</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='Label_Semi_Private']</value>
      <webElementGuid>5d23619b-09f4-46f9-80ff-710ac790eec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='Pre_Quote_Select_Option']/label)[4]</value>
      <webElementGuid>34c889ce-aede-4736-a5a6-44f5ce0750fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::label[1]</value>
      <webElementGuid>1d6e0fc8-0d17-4327-83e3-810f732e288e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefit level'])[1]/following::label[2]</value>
      <webElementGuid>72c06931-6841-4aaa-8acd-dba5f54f9a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ward'])[1]/preceding::label[1]</value>
      <webElementGuid>19546b0d-d3b5-45d9-8e7d-da88b18fa67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label</value>
      <webElementGuid>dba70126-ada5-4875-bccb-a99dfca1043d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'Label_Semi_Private' and (text() = 'Semi-Private' or . = 'Semi-Private')]</value>
      <webElementGuid>a40272fc-b42b-4d82-a4e0-a5a477efe183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
