<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Ward</name>
   <tag></tag>
   <elementGuidId>3a34ae52-efe0-4b42-90e0-1e7e13dacd19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='Label_Ward']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Label_Ward</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7aebe39c-da3b-4633-a3d2-bb85cd76036f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_en</value>
      <webElementGuid>1d3c9424-9dda-4511-9750-47d77cd1becf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Guarantee_Level_Ward</value>
      <webElementGuid>578ffe2c-0dbd-41a0-b546-0a33ed0d36b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Label_Ward</value>
      <webElementGuid>fe16e9a2-3c66-481a-b30f-41ed1e3144cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ward</value>
      <webElementGuid>ff217a12-e079-487e-873c-2bd690c79068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Label_Ward&quot;)</value>
      <webElementGuid>163ee2a9-6fc3-4797-b529-59dcd932f95e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='Label_Ward']</value>
      <webElementGuid>382d0789-28cf-4f92-bdfe-34153b52f597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='Pre_Quote_Select_Option']/label)[5]</value>
      <webElementGuid>7a903e8f-01f4-4140-ba93-d161cda170e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semi-Private'])[1]/following::label[1]</value>
      <webElementGuid>12e6a52f-8623-40fe-b60c-bd9e1343c31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::label[2]</value>
      <webElementGuid>4970f0cc-dc01-42f4-b5b2-f8df55164ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Benefit'])[1]/preceding::label[1]</value>
      <webElementGuid>3d0c8991-3368-4557-bc66-008a7f39fc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/label</value>
      <webElementGuid>0a806851-afc3-4714-bbc2-9eeba39fb3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'Label_Ward' and (text() = 'Ward' or . = 'Ward')]</value>
      <webElementGuid>4e591028-117c-453e-aed9-32596b7d3716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
