<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Gender Male Female</name>
   <tag></tag>
   <elementGuidId>bbfbf415-2770-487d-8640-f01ae06e9124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Pre_Quote_Product_Genders']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pre_Quote_Product_Genders</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>de0fde84-e8d0-428b-a32c-c52c61d31f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pre_Quote_Product_Gender</value>
      <webElementGuid>69d836f7-4f16-41a3-a944-f45e0f6078d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pre_Quote_Product_Genders</value>
      <webElementGuid>99444faa-f8e2-4ed6-a009-cb4c116c5698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_dashline</value>
      <webElementGuid>61bf4dba-b3c9-4847-b6d3-e0a6baba929a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gender Male Female</value>
      <webElementGuid>aaea1c34-96e4-4530-939b-a135de91ce91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pre_Quote_Product_Genders&quot;)</value>
      <webElementGuid>62bf7143-f30c-4d03-967b-d765515ae64b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Pre_Quote_Product_Genders']</value>
      <webElementGuid>6172f7b6-9bfc-4120-aca3-38d6a216a0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Pre_Quote_Product_Details_Main']/select</value>
      <webElementGuid>e8cf126c-0f60-430c-8f5b-77eb8f9445e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='year old'])[1]/following::select[1]</value>
      <webElementGuid>2bd068a1-ca9b-46e2-bff6-ee8499aad821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am a'])[1]/following::select[1]</value>
      <webElementGuid>db0e76cb-daa6-44f0-adf1-571c7087dcb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(As a policy holder, you must be aged 18 or above. You can add other family members later.)'])[1]/preceding::select[1]</value>
      <webElementGuid>6a075e91-1c25-47e6-8dda-254ed5d3c515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter the age between 18 to 69'])[1]/preceding::select[1]</value>
      <webElementGuid>6e510e7f-b40b-4282-aa3e-86836892b2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>c8c007dd-afd9-4b74-ada5-3785ba66ce4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Pre_Quote_Product_Gender' and @id = 'Pre_Quote_Product_Genders' and (text() = 'Gender Male Female' or . = 'Gender Male Female')]</value>
      <webElementGuid>d62b98d8-6b21-4152-994f-ebe213fcaa8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
