<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HK24,789.77</name>
   <tag></tag>
   <elementGuidId>9f985a1b-3f64-4665-95b7-37d21856c059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='total_pre_quote_price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#total_pre_quote_price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2afa5b95-9c3f-4a32-85b5-4e1133865e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total_pre_quote_price</value>
      <webElementGuid>0a8fe37b-623b-4b07-ae8d-d096d993416f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HK$24,789.77</value>
      <webElementGuid>6275dfa8-a01a-4276-ab54-f51fff813a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total_pre_quote_price&quot;)</value>
      <webElementGuid>10c990e4-2d6f-4b1c-8bfe-0654ed288410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='total_pre_quote_price']</value>
      <webElementGuid>5c783ab0-c524-4cef-832c-aa074b5daea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Pre_Quote_Count']/div/span</value>
      <webElementGuid>437b1c20-1e22-4c5c-9458-a0889c4aceae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$'])[2]/following::span[1]</value>
      <webElementGuid>bf3ae987-2050-417c-a605-d14baaa6de99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discount'])[1]/following::span[1]</value>
      <webElementGuid>b6b768e5-b5a1-4b07-b04f-5f1293ccda0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your total'])[1]/preceding::span[1]</value>
      <webElementGuid>e2adc4aa-8ba2-47d2-8f78-3b412f29787e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$24,765.00'])[1]/preceding::span[1]</value>
      <webElementGuid>99450e10-8077-42a3-aa72-5e9d1dbca768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HK$24,789.77']/parent::*</value>
      <webElementGuid>5b4a0531-3004-4d5e-b9e3-225a3b9b0c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[3]/div/span</value>
      <webElementGuid>08c89db9-e856-446d-8746-342b22e2b0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'total_pre_quote_price' and (text() = 'HK$24,789.77' or . = 'HK$24,789.77')]</value>
      <webElementGuid>66d0bda3-0bdc-4afc-88c0-d1ae670dc3c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
