<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yearly</name>
   <tag></tag>
   <elementGuidId>e356fb84-47ec-4e79-9ef1-140f82b61c5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='S_Year_Text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#S_Year_Text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4764978-0bfc-4683-a66d-7e6f79bba00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>S_Year_Text</value>
      <webElementGuid>029e31bf-01e0-487f-977e-a0f6b3c20a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yearly</value>
      <webElementGuid>4a0ff7ee-598f-495f-9bed-40fe0826e6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S_Year_Text&quot;)</value>
      <webElementGuid>89e91152-b6db-4fbf-9972-b47aea41d656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='S_Year_Text']</value>
      <webElementGuid>927c8b62-3f61-4389-ac33-861e7d93edcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='label_Payment_Year']/span</value>
      <webElementGuid>39eb79a7-1ad8-4159-b40a-b4464f0bd9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Mode'])[1]/following::span[1]</value>
      <webElementGuid>1bf6e954-ce38-48f8-bd49-d8486c7421f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='此優惠不適用於已退休或終止團體計劃之團體會員'])[1]/following::span[1]</value>
      <webElementGuid>eb32d500-526c-40af-8d09-49cceea866a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly'])[1]/preceding::span[2]</value>
      <webElementGuid>894c08b1-375b-48c4-8960-2a82ec820c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('First 2 months', &quot;'&quot;, ' subscription and levy will be charged as initial payment')])[1]/preceding::span[4]</value>
      <webElementGuid>7757205b-1223-4d33-8de2-c757c8adbd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yearly']/parent::*</value>
      <webElementGuid>e266580a-3da3-4cda-81c4-e0fb3772913d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/label/span</value>
      <webElementGuid>33e9a124-a0be-42d3-81fa-577472cb2f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'S_Year_Text' and (text() = 'Yearly' or . = 'Yearly')]</value>
      <webElementGuid>2d70f43a-712a-4fb6-b1fd-bf0d3adcc08b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
