<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>f16f03e2-e805-475e-874f-e2f77f8b04a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='go_Enroll']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#go_Pre_Quote</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Next' or . = 'Next')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>631114a2-21ac-46aa-b66a-394f3f5fee38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go_Pre_Quote</value>
      <webElementGuid>b7c60ba6-8d43-4377-9509-0b8779d64ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quote_now_btn</value>
      <webElementGuid>d3705b96-443c-4181-86d6-8360aece3c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>64dfa00e-68a5-4f09-b2e6-0ae356f82188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go_Pre_Quote&quot;)</value>
      <webElementGuid>330f587a-3358-4bc7-8919-90467ab7e199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='go_Pre_Quote']</value>
      <webElementGuid>32c13315-01ae-445c-acf4-bd55306977eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guideContainer-rootPanel-panel1641523787568-panel-guidetextdraw_59952898__']/div/div[2]/button</value>
      <webElementGuid>6f937920-69ca-4aed-9c79-e19bcf5a2200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='As a policy holder, you must be aged 18 or above.'])[1]/following::button[1]</value>
      <webElementGuid>cd63317f-2713-4652-9e18-106bf0b0db36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid Membership No.'])[1]/following::button[1]</value>
      <webElementGuid>f5225f51-df36-4c3a-8d6e-d43883e829bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark: This page will be expired after 15 minutes of inactivity.'])[1]/preceding::button[1]</value>
      <webElementGuid>f62e23a0-d6cb-4717-abd1-bc91b0348caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrolment hotline'])[1]/preceding::button[1]</value>
      <webElementGuid>359e47c6-058b-4f70-a4eb-78b9de1f2ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>64bcd984-9ff7-42a9-af96-7df399742b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/button</value>
      <webElementGuid>3cf1cbad-9f18-4869-a2e8-809e81873c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'go_Pre_Quote' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>b91b6493-ec29-453f-80a8-053123e8be94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
