<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get my quote</name>
   <tag></tag>
   <elementGuidId>402b1301-5443-436d-80a5-7c09ab134d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='get_Quote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#get_Quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e62174ae-90ef-47a8-a8af-8551b2c7e4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>get_Quote</value>
      <webElementGuid>68f31c45-bd95-4284-818e-e5ab1e7a7885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>quote_now_btn</value>
      <webElementGuid>8489dbbf-ff83-4afb-b93f-59f4c4485e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get my quote</value>
      <webElementGuid>93b277d2-d8f2-484f-927b-aafdd2827ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;get_Quote&quot;)</value>
      <webElementGuid>91c8ea36-8e57-46f0-9c02-ab176d4f89ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='get_Quote']</value>
      <webElementGuid>7788ec48-cfb8-4f57-a150-8c9fbf17e13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guideContainer-rootPanel-panel_322752692-panel-panel-panel-guidetextdraw_2087322221__']/div/button</value>
      <webElementGuid>a866cef5-3697-4a39-906c-d24004343520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Online'])[1]/following::button[1]</value>
      <webElementGuid>8e74475f-4e3c-4259-9eaa-52d4529d2739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify'])[1]/following::button[2]</value>
      <webElementGuid>1872b77b-30a4-4245-9949-314decee7cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your subscription and levy (after discounts)'])[1]/preceding::button[1]</value>
      <webElementGuid>5e3e8d78-956a-4242-ad13-ca2f45b7bdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$'])[1]/preceding::button[1]</value>
      <webElementGuid>288f3d8e-4a5e-4adf-a38d-87db6f8a16b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get my quote']/parent::*</value>
      <webElementGuid>bc8571de-5099-488f-b335-1c3af2443c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/button</value>
      <webElementGuid>5f9542f4-0070-4520-962e-e57185415406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'get_Quote' and (text() = 'Get my quote' or . = 'Get my quote')]</value>
      <webElementGuid>bca08e67-c011-4285-8da9-ebb4714e39dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
