<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next (2)</name>
   <tag></tag>
   <elementGuidId>51f20170-bd65-46c7-b05d-51d998736293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='q0_next']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___widget</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5917650d-7a64-4855-9679-1236add7e8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-default button-medium Button</value>
      <webElementGuid>ae5949ad-9cf3-40ab-8075-8dac85931b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6b58a51-d41f-4424-971a-e1d27fed0a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___widget</value>
      <webElementGuid>51c35fa1-68ee-4416-acf7-35db042ef2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___jqName</value>
      <webElementGuid>85c62fb5-71db-4ced-a79d-62dad07ff53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9be00309-ad2f-4761-89ff-3b195cc66af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>96803b99-6d76-4d54-8d55-a28f5778b340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        
        Next
    </value>
      <webElementGuid>9e667682-5413-4e81-8947-af5ef5b8de9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___widget&quot;)</value>
      <webElementGuid>3c9a80a5-fc4c-4009-9234-d9568c4f24d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___widget']</value>
      <webElementGuid>f5f0908f-3e4e-4c4c-927c-10489fe59cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308__']/div/button</value>
      <webElementGuid>83dd9301-5312-4caa-b448-ed83ea4fbb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[2]/following::button[1]</value>
      <webElementGuid>2c620775-defd-417a-92a9-b5258a3841b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$24,789.77'])[5]/following::button[2]</value>
      <webElementGuid>39b65e00-0e56-4d30-896e-de723862062c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark: This page will be expired after 15 minutes of inactivity.'])[4]/preceding::button[1]</value>
      <webElementGuid>360e80de-ebee-4d16-956f-faa2311cb327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div[7]/div/div/div/button</value>
      <webElementGuid>cf3f0873-ac3a-4f8c-89e5-b4d48b98a358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___widget' and @name = 'guideContainer-rootPanel-panel1641789048390-panel_copy-guidebutton_1137967308___jqName' and (text() = '
        
        Next
    ' or . = '
        
        Next
    ')]</value>
      <webElementGuid>b4213912-dd3f-4449-97e8-1b3d2d04cd7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
