<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Promotion Code (if any)_Pre_Quote_Discount</name>
   <tag></tag>
   <elementGuidId>dae3f7a8-6f93-4fbc-bf4c-48873e1a5ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Pre_Quote_Discount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pre_Quote_Discount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9698da3c-e0ed-4821-a829-2a701378bb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8cfccd43-0eba-475e-a813-579bd78aa6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_dashline</value>
      <webElementGuid>c88129aa-c7e9-45a8-aec1-983c7cbe8d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pre_Quote_Discount</value>
      <webElementGuid>d3c1ac5d-7a18-456c-b672-e66eb27e99b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input here</value>
      <webElementGuid>7e9e9ec7-cba0-4381-8f30-5897f7f84026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pre_Quote_Discount&quot;)</value>
      <webElementGuid>196986f7-6c82-47d3-ac25-cdc9ca4168d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Pre_Quote_Discount']</value>
      <webElementGuid>85041e16-7e46-47b0-a0d1-64f29090094c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Promotion_Offer']/input</value>
      <webElementGuid>e9b8dc7e-0cb2-4146-9f13-5cc21139ffc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>57987d8b-ec94-4992-bd13-c58934b09d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Pre_Quote_Discount' and @placeholder = 'Input here']</value>
      <webElementGuid>84e38580-0a64-4a34-b829-4556ef884fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
