<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Membership No. of Exisiting Group Mem_29c7a5</name>
   <tag></tag>
   <elementGuidId>4febf44c-5134-4873-baa7-eec4d076a95f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M_MembershipNo_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#M_MembershipNo_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05b36976-a646-41e8-a404-4600fa725d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4be3e62-1afa-43f6-8dbf-59ed9ba831d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M_MembershipNo_1</value>
      <webElementGuid>b2f0962c-61e4-4d56-a803-c44eab8faf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>72c14cba-4b20-432e-b128-484717b8c923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43197b51-2a47-4b65-82c1-29053580be00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M_MembershipNo_1&quot;)</value>
      <webElementGuid>2aed26f6-2a01-4946-8818-07d43e955271</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M_MembershipNo_1']</value>
      <webElementGuid>c576b5fd-478e-43ae-a1ff-ab41f2f71041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M_MembershipNo']/input</value>
      <webElementGuid>b5b14528-8ac6-4740-a13d-0758963bcf82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>3f5e8d2f-96cf-4d33-a61a-3038344de8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'M_MembershipNo_1']</value>
      <webElementGuid>82a2ba7a-595f-488c-a0c0-33f8d53622e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
