<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__S_Last_Name_Eng</name>
   <tag></tag>
   <elementGuidId>4e8e5ef1-fc14-40a1-ad51-f454e9f55ec7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='S_Last_Name_Eng']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#S_Last_Name_Eng</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>084236e1-b0c7-47b6-96c4-eb29126fd8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f31be08-232e-48b6-b3e7-970e674ba9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>S_Last_Name_Eng</value>
      <webElementGuid>5d4d7231-e5b1-42bc-9851-0e81fbbebb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control check_english</value>
      <webElementGuid>39d383b8-ce11-47d4-88d2-392f2b72a23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>da7a71c5-b9ce-4eba-9e29-6fed6aaebbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S_Last_Name_Eng&quot;)</value>
      <webElementGuid>e6a46aaf-9776-471e-8d0e-83285300a663</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='S_Last_Name_Eng']</value>
      <webElementGuid>433ea04a-bcda-49ed-892c-83557bce2b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Self_Last_Name_Eng']/input</value>
      <webElementGuid>7de94f09-08e6-4618-b4d1-8f81a2b72659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>6bbb0624-3f12-48e1-86fe-57a4632907d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'S_Last_Name_Eng']</value>
      <webElementGuid>fb55eb03-f7f7-42e6-9ac1-fb9fe12fccbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
