<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height_height_value</name>
   <tag></tag>
   <elementGuidId>325ccba3-a90b-43f5-bfb4-bd6822e8ce1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='height_value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#height_value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b949add6-f327-457a-8294-a5a4ba3dcc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0db61caf-1753-44ed-92f7-0c64c6dfaaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>height_value</value>
      <webElementGuid>19553835-817e-4aad-b423-196cc104c290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;height_value&quot;)</value>
      <webElementGuid>453aeae3-d9e7-41e6-a843-1e003e113582</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='height_value']</value>
      <webElementGuid>fa9f40bc-06e3-4067-b7c0-4ced233b8083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UW_BMIQ']/div/div[2]/div/div/input</value>
      <webElementGuid>8dc64bdc-747a-4592-9ef3-c5ff3125315e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>02fec2f9-588e-4a6d-b64c-e10704ec91e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'height_value']</value>
      <webElementGuid>24b61836-6bc6-4fd9-a805-5396acc32606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
