<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight_weight_value</name>
   <tag></tag>
   <elementGuidId>bd443f47-8fb1-4aa8-a93c-e0e380590082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='weight_value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#weight_value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae0893e1-a7ea-4440-bcfd-be1f4eb11c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81c33f25-e899-466e-b1c5-94b22b846c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weight_value</value>
      <webElementGuid>e7e908e0-77a6-436e-82fe-53b4eacfe802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weight_value&quot;)</value>
      <webElementGuid>d2354985-37c4-41e3-8f1c-4d257fd6b277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='weight_value']</value>
      <webElementGuid>3f5d5713-070b-42f3-b658-ce740478d94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UW_BMIQ']/div/div[2]/div/div[2]/input</value>
      <webElementGuid>ab7f8346-a858-40ca-b0c7-f71c370867b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>1ac2953b-e39a-47a5-b679-d1ff3cc251cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'weight_value']</value>
      <webElementGuid>93438348-6efe-4132-a5fa-6eec17ffd64b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
