<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Membership No. of Exisiting Group Member_M_MembershipNo_2</name>
   <tag></tag>
   <elementGuidId>2c3ff331-dc54-442d-b5eb-e344522fa109</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='M_MembershipNo_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#M_MembershipNo_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce98267b-7469-4242-868b-c06f63ab3430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56220e89-af73-485e-9e68-174b1dcfd43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>M_MembershipNo_2</value>
      <webElementGuid>57f4a5eb-2f75-4bbe-96f8-b91e28f2270a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>17d4d724-f479-4f15-9054-3d256dd47d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58f43327-d5c6-46b8-abaa-c3df55ff6a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;M_MembershipNo_2&quot;)</value>
      <webElementGuid>3ca1a745-089a-4d2e-a40f-32e22edfc510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='M_MembershipNo_2']</value>
      <webElementGuid>e59cc53f-7a6b-40e1-a0e6-bdb736b3f07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='M_MembershipNo']/input[2]</value>
      <webElementGuid>60ed3177-e7f2-4293-9e61-0d175a99b49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/div/div/input[2]</value>
      <webElementGuid>8d334178-320f-4e69-b452-3f722c296028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'M_MembershipNo_2']</value>
      <webElementGuid>a51ca969-cf05-48c9-ba84-616177974b26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
