<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Gender Male Female</name>
   <tag></tag>
   <elementGuidId>32b18459-1cf5-476a-a378-6230ec5da35a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Pre_Quote_Product_Genders']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pre_Quote_Product_Genders</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>457a7f2b-b42e-4968-a13d-6bbb087c66b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Pre_Quote_Product_Gender</value>
      <webElementGuid>922affda-080c-46b6-b389-01c0e0404490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pre_Quote_Product_Genders</value>
      <webElementGuid>fb83d8bf-9584-4122-ba45-638d56533253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file_dashline</value>
      <webElementGuid>977ac397-a785-4048-be2f-61bfc6a0da46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gender Male Female</value>
      <webElementGuid>1fb9ee09-c4cf-4301-b05c-317aaeef38b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pre_Quote_Product_Genders&quot;)</value>
      <webElementGuid>a37289b9-cd43-4fd4-a20c-8c1171246bc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Pre_Quote_Product_Genders']</value>
      <webElementGuid>a692d887-2d6c-4b55-8df9-21fcb801d523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Pre_Quote_Product_Details_Main']/select</value>
      <webElementGuid>700fa88a-18b5-4cc7-a831-2f1282e52aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='year old'])[1]/following::select[1]</value>
      <webElementGuid>29065305-a6c8-4e43-a23d-eb300ca69775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I am a'])[1]/following::select[1]</value>
      <webElementGuid>93cbbb9e-63ff-4549-bb69-a9ec38cc825e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(As a policy holder, you must be aged 18 or above. You can add other family members later.)'])[1]/preceding::select[1]</value>
      <webElementGuid>de2809df-9b4c-473b-8ad7-f22953c5df77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter the age between 18 to 69'])[1]/preceding::select[1]</value>
      <webElementGuid>f02f76ee-a2fc-4977-a9ec-98a02f3669a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>b16fe2b5-5be7-4dca-81ef-b3818070da75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Pre_Quote_Product_Gender' and @id = 'Pre_Quote_Product_Genders' and (text() = 'Gender Male Female' or . = 'Gender Male Female')]</value>
      <webElementGuid>e9706738-77d9-4805-aefb-fbec5c9b9be0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
