<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select Terminated employment</name>
   <tag></tag>
   <elementGuidId>5019ecd0-c629-4ed7-a6e7-68daf9600b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='S_Eligibilitys']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#S_Eligibilitys</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>08ae4fcf-13ee-4264-aca5-73f174540bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>S_Eligibility</value>
      <webElementGuid>1700335c-16b8-453c-a2fb-f1c029689334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>S_Eligibilitys</value>
      <webElementGuid>3b487624-dd65-4f02-b34f-e320ea734c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>59971b54-6140-4a88-8b84-fac1dfe1eac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Please Select Terminated employment Newly covered under Bupa group scheme Bupa group scheme is renewed within 60 days Retired Newly married or has a new born child Reaching age 70</value>
      <webElementGuid>86bc5038-50bc-40b5-a817-8c28ef1fa0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;S_Eligibilitys&quot;)</value>
      <webElementGuid>c2562ac7-2254-4532-b202-c4ead9a902ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='S_Eligibilitys']</value>
      <webElementGuid>2eea084a-0075-4088-bb21-f25583c57ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Self_Eligibility']/select</value>
      <webElementGuid>86101930-58c9-4db3-a756-a726218b7eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>4c7ec0b3-3975-4e3b-a98d-68aa4d788e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Date of Birth doesn', &quot;'&quot;, 't match with the current group membership record')])[1]/following::select[1]</value>
      <webElementGuid>f9f188e9-4273-429c-b92d-2c10dd410f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Last date of Bupa Group Health Insurance Scheme', &quot;'&quot;, 's Membership')])[1]/preceding::select[1]</value>
      <webElementGuid>68ca692c-8301-4641-82e5-d5c9894872b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>561ed4b2-76ad-4ec3-8a99-b9408a34109d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'S_Eligibility' and @id = 'S_Eligibilitys' and (text() = ' Please Select Terminated employment Newly covered under Bupa group scheme Bupa group scheme is renewed within 60 days Retired Newly married or has a new born child Reaching age 70' or . = ' Please Select Terminated employment Newly covered under Bupa group scheme Bupa group scheme is renewed within 60 days Retired Newly married or has a new born child Reaching age 70')]</value>
      <webElementGuid>c79fe259-d188-4d6b-b6ca-43581c9dd883</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
