<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HK24,789.77</name>
   <tag></tag>
   <elementGuidId>ea781bcc-243a-4552-87c9-5e4dcf018236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='total_Enrollment_price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#total_Enrollment_price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2f5c42fd-571d-4e68-bab6-5e78c34f94f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total_Enrollment_price</value>
      <webElementGuid>c8242290-0e04-4c28-b120-2bff88447a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HK$24,789.77</value>
      <webElementGuid>4e0c978e-8018-4f14-9ccc-871897a3bcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total_Enrollment_price&quot;)</value>
      <webElementGuid>04685314-053e-41ec-b3de-0d18174aa45d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='total_Enrollment_price']</value>
      <webElementGuid>2286811d-c525-4445-b2f6-10859740c772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Enrollment_Count_Body']/div/div/span</value>
      <webElementGuid>010a87ab-9636-4b72-a23d-13bd51264bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your subscription and levy (after discounts)'])[3]/following::span[1]</value>
      <webElementGuid>1226c4c6-9247-4e90-807b-5597e586adf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$'])[8]/following::span[2]</value>
      <webElementGuid>e6a94cc6-d161-4e68-90cf-5053914ac028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$24,789.77'])[4]/preceding::span[1]</value>
      <webElementGuid>e115bea0-0990-48bd-80bd-82d5a3912b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>158d673c-f922-4e04-8481-9ab2ebd236b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'total_Enrollment_price' and (text() = 'HK$24,789.77' or . = 'HK$24,789.77')]</value>
      <webElementGuid>f3f8c31d-dba4-4e2d-8de4-dd5460d0dcee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
