<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HK24,765.00</name>
   <tag></tag>
   <elementGuidId>38d77bd8-c9cb-4ff6-978c-a9b33133fedd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sum_pre_quote_price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sum_pre_quote_price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5aee98f5-bb62-4606-bae1-c995ccbf5640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sum_pre_quote_price</value>
      <webElementGuid>55913e76-55e7-44bd-86da-f2e7d57db05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HK$24,765.00</value>
      <webElementGuid>e22bc52f-07b6-4934-aaf7-76467c556bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sum_pre_quote_price&quot;)</value>
      <webElementGuid>3c4273dd-a0a4-43b4-abc5-1a4ac6089b93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='sum_pre_quote_price']</value>
      <webElementGuid>b11bfe6c-fc45-455f-99ac-f1130110d45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Pre_quote_Count_display']/div[2]/div/span[2]</value>
      <webElementGuid>2a3bbff8-e943-43b3-a7d2-44f6bb0b4a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total subscription'])[1]/following::span[1]</value>
      <webElementGuid>732aa6bd-7420-49d8-95d9-0472ece60e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-HK$0.00'])[1]/following::span[2]</value>
      <webElementGuid>10e14c7e-a406-44d6-baa7-a0094a216eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Levy (0.1%)'])[1]/preceding::span[1]</value>
      <webElementGuid>484a1eef-1059-48d2-bfb8-b67613d4d49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HK$24.77'])[1]/preceding::span[2]</value>
      <webElementGuid>8e1583ba-2fdd-464a-ae96-3b6e59a98f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span[2]</value>
      <webElementGuid>7dc3cd33-3d77-462c-9a43-cdb30ddcd2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'sum_pre_quote_price' and (text() = 'HK$24,765.00' or . = 'HK$24,765.00')]</value>
      <webElementGuid>e2219026-6bac-48bb-b4be-7bc37360cfa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
