<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_remove_Amount_General</name>
   <tag></tag>
   <elementGuidId>540bec72-03f7-4ff4-8649-17b59ad9e503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Amount_General</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Amount_General']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3909a789-302b-4681-b8d8-1e41e773dadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Amount_General</value>
      <webElementGuid>ecbc5b8f-0c7d-4106-bad4-02c90f606695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Amount_General</value>
      <webElementGuid>b28a3311-02a6-41a2-b975-373aae41ccc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>secf.model.Amount_General</value>
      <webElementGuid>44472768-434e-42fa-ac3d-e96e04bf9d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{true: 'form-control--error'}[steps.step1['Amount_General'].$invalid &amp;&amp; (steps.step1['Amount_General'].$touched || steps.step1.$submitted)]</value>
      <webElementGuid>7d5f3153-bf74-4c98-8d0c-c4faf98294e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[0-9]+(\.[0-9]{1,2})?$/</value>
      <webElementGuid>b14e8fe9-f582-490f-be85-32a90bf7dd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>secf.isBusy || !(secf.isMemberSelected &amp;&amp; secf.isShowGeneralAmount)</value>
      <webElementGuid>992eb17d-cdb1-426e-b00f-bb8a53180d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>secf.isMemberSelected &amp;&amp; secf.isShowGeneralAmount</value>
      <webElementGuid>73e5a54a-20f2-4178-9579-ff515226a00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>secf.clearCustomErrors(['MinReceiptAmount'], steps); secf.isValidTotalAmount(steps)</value>
      <webElementGuid>40de539d-070d-4c0b-8c39-745cd330ed02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2e38c759-cab1-4b05-889f-e6f1fdf9650d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>70ccd13e-f56c-4cf6-a13d-6f584d9d1a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-max</name>
      <type>Main</type>
      <value>99999999</value>
      <webElementGuid>a1c78f5f-495a-49ab-92ab-60af95fd89a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>secf.clearCustomErrors(['MinReceiptAmount'], steps)</value>
      <webElementGuid>cf3bc0b3-7631-4ca9-b242-f411876263ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4f42c130-0407-49d2-8769-6c102123695d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-isolate-scope ng-valid-min ng-valid-max ng-valid-pattern ng-valid-min-receipt-amount ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
      <webElementGuid>71d85dd2-cf47-4873-8d67-4deed0450d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>90ce6bdd-a9d0-42f2-b17e-88f73da0b6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b6f1a664-e53d-4fa8-bede-b33eb4ad17d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Amount_General&quot;)</value>
      <webElementGuid>b79e7912-1863-4cbf-b960-38c51528a7c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Amount_General']</value>
      <webElementGuid>c1182ece-7063-43b4-82e3-4a2801de2382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>cd2c52aa-57c4-4de0-8df1-d394c2df2780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Amount_General' and @id = 'Amount_General' and @type = 'number' and @placeholder = '0']</value>
      <webElementGuid>e5a28fcb-4740-4c21-a2e5-c5edd1712f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
