<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of treatment_DATEOFTREATMENT</name>
   <tag></tag>
   <elementGuidId>881c9dd2-b9ca-4c19-8340-3bc8231a93c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DATEOFTREATMENT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DATEOFTREATMENT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9621d31-4b3f-40a6-aa29-33f3711a6366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-scope ng-isolate-scope ng-empty ng-valid-date-before ng-valid-date-after ng-valid-date-after-specified-date ng-invalid ng-invalid-required</value>
      <webElementGuid>59b4fb9b-2f0c-4d4f-bead-9d6ab20a99a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1da5b02-5177-47e8-984b-cde807c086ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY (e.g. 31/01/2000)</value>
      <webElementGuid>e4f8d700-2230-4d83-a9a8-e9e9e038ddf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DATEOFTREATMENT</value>
      <webElementGuid>73847694-3417-48ae-8cd3-0f74cb7a4890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DATEOFTREATMENT</value>
      <webElementGuid>04e86f5b-a7a7-4c99-9372-68357c130564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>secf.form.DATEOFTREATMENT</value>
      <webElementGuid>618fa731-753e-4252-8b7f-f8e01fd4093c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{true: 'form-control--error'}[steps.step1['DATEOFTREATMENT'].$invalid &amp;&amp; (steps.step1['DATEOFTREATMENT'].$touched || steps.step1.$submitted)]</value>
      <webElementGuid>b79dc51e-13d3-42aa-9b88-710ed7112ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>end</name>
      <type>Main</type>
      <value>today</value>
      <webElementGuid>67f4bfcf-ed92-4f80-b745-e0d496c39aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>secf.isBusy || !secf.isMemberSelected</value>
      <webElementGuid>6be8de0f-b682-400d-87d8-e3654b51540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41df0f96-69de-4229-af30-489bcef38c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>secf.clearCustomErrors(['required', 'dateBefore', 'dateAfter', 'dateAfterSpecifiedDate'], steps)</value>
      <webElementGuid>eb19934f-8771-4f1e-b606-c206da436a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>secf.updateFormContentByClaimItem()</value>
      <webElementGuid>a01a32b7-82d5-40b1-b548-a48d38073f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6bf32efb-3cee-4c6e-81cd-82ac328077e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>v-date-before</name>
      <type>Main</type>
      <value>2022/12/14</value>
      <webElementGuid>345593f8-9e46-47a5-9a2a-7ac701f19994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>v-date-after</name>
      <type>Main</type>
      <value>secf.dateXDaysFromNow</value>
      <webElementGuid>954c23b2-16f7-4ab5-a19c-55ee04c7148f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>v-date-after-specified-date</name>
      <type>Main</type>
      <value>23/07/2018</value>
      <webElementGuid>d12adab0-920e-4584-be77-737cc4113c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>49a85f00-f769-4bbe-9f15-38de8cfc0917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8f582d8e-8868-4360-b2e3-de63534d6dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DATEOFTREATMENT&quot;)</value>
      <webElementGuid>5fc1202a-140d-4871-941a-9ce9ebe3207d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DATEOFTREATMENT']</value>
      <webElementGuid>3ac35cbb-1ff5-45af-8e79-b12a1ed22cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-transclude/input</value>
      <webElementGuid>1cc0db11-d1f3-4805-969f-79f4b567a458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'DD/MM/YYYY (e.g. 31/01/2000)' and @name = 'DATEOFTREATMENT' and @id = 'DATEOFTREATMENT']</value>
      <webElementGuid>38985b0d-d462-4860-9e55-7a3e4882e1ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
