<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_SYMPTOMDATE</name>
   <tag></tag>
   <elementGuidId>21e742e8-f9d8-406c-bd8c-1f0506681767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SYMPTOMDATE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SYMPTOMDATE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caf7660f-2246-4c5c-8660-00c87f237d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-scope ng-empty ng-valid-date-before ng-valid-required</value>
      <webElementGuid>317cd569-b305-40b6-bdb2-1d6089c61b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>593a6f89-e3b2-460a-a95b-7ce9e8e60997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY (e.g. 31/01/2000)</value>
      <webElementGuid>9c291484-de53-4a4c-a5e5-e21f185a9510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>secf.form.SYMPTOMDATE</value>
      <webElementGuid>8872a70f-e4f1-4358-bbff-051ed51e60b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SYMPTOMDATE</value>
      <webElementGuid>43630183-714c-4d8d-a136-0575a06dd25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SYMPTOMDATE</value>
      <webElementGuid>e274cbcc-1332-4c8a-80a8-826755606c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{true: 'form-control--error'}[steps.step1['SYMPTOMDATE'].$invalid &amp;&amp; (steps.step1['SYMPTOMDATE'].$touched || steps.step1.$submitted)]</value>
      <webElementGuid>e15764c1-5308-4405-9ff7-ee6bf269cc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>secf.isBusy || !secf.isMemberSelected</value>
      <webElementGuid>ca97adc3-26be-4bf8-b80b-32222ab115d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>end</name>
      <type>Main</type>
      <value>today</value>
      <webElementGuid>4b5e1e53-847d-4ec1-aaa6-b0cc1d40b26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>secf.model.diagnosis.ISSHOWSYMPTOMDATE == 'Y'</value>
      <webElementGuid>05d6864f-19b9-4f1e-93a1-23ad788f7a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-v-date-before</name>
      <type>Main</type>
      <value>{{secf.form.DATEOFTREATMENT|date:'dd/MM/yyyy'}}</value>
      <webElementGuid>bfee4c13-c8c0-4171-af74-f3831292dc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ad849be7-da54-4554-ba42-6c5096602b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28cf5b52-a197-4797-9300-c46c03eeb602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>v-date-before</name>
      <type>Main</type>
      <value>2022/12/07</value>
      <webElementGuid>ce7184af-9efe-4e92-a56f-a71ebf21c9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SYMPTOMDATE&quot;)</value>
      <webElementGuid>69df1b3c-5489-4735-aebd-1c2f560690fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SYMPTOMDATE']</value>
      <webElementGuid>3e0152fc-7f95-475c-a78a-0dc73247aca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/ng-transclude/input</value>
      <webElementGuid>b1c21505-870e-4b7a-b1d2-2bbddf3942a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'DD/MM/YYYY (e.g. 31/01/2000)' and @name = 'SYMPTOMDATE' and @id = 'SYMPTOMDATE']</value>
      <webElementGuid>74bf1394-cdfe-4ea8-ada8-0c162c91bb6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
