<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectGeneral Practitioner</name>
   <tag></tag>
   <elementGuidId>35eca9a9-524c-4814-a98b-640e1558a5ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#natureOfReimbursement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='natureOfReimbursement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41fc4d43-4c88-497a-8158-a09f355cc4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>natureOfReimbursement</value>
      <webElementGuid>0896cbdb-a6af-43d3-bc79-555376168935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>natureOfReimbursement</value>
      <webElementGuid>c9fd36de-ab07-4aa1-a968-6a3cb0c49570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>secf.model.natureOfReimbursement</value>
      <webElementGuid>522cb635-1d66-45fd-83bf-bba42f2e1d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{true: 'form-control--error'}[steps.step1['natureOfReimbursement'].$invalid &amp;&amp; (steps.step1['natureOfReimbursement'].$touched || steps.step1.$submitted)]</value>
      <webElementGuid>90c7f5ee-c2a5-4635-ac8f-8cbcdd2b99d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>k as v for (k, v) in secf.benefitHeadList[secf.memberNumber]</value>
      <webElementGuid>89fe4a28-e28d-4732-a2cd-9c1126e40c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ceb1e45b-1a1f-4479-90f3-682ca2c5c70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>secf.isBusy || !secf.isMemberSelected</value>
      <webElementGuid>8fc89383-ed5f-4fe2-8885-03c5632b1e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>secf.clearCustomErrors(['natureOfReimbursementRequired'], steps)</value>
      <webElementGuid>42911190-ef13-4679-8f4e-8eb3d8841193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>secf.updateFormContentByClaimItem()</value>
      <webElementGuid>735e68ab-7e42-45fb-b540-da9c710b56e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control select__control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>32099ac2-ec9b-4f6c-974b-8546015ea008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5d1f0b93-07ed-40e3-8578-7e0a8bf1f8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3b3dfae-498d-4637-a406-26aea7f39a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectGeneral PractitionerSpecialistPrescribed Western MedicationDiag. Imaging &amp; Lab TestsChinese HerbalistBonesetterPhysiotherapistChiropractorPrescribed Western Medication (Pharmacy)</value>
      <webElementGuid>6264903a-a246-4f28-8791-20dbb99aaf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;natureOfReimbursement&quot;)</value>
      <webElementGuid>1d9aba72-5bcb-4d05-932c-68b62fa01269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='natureOfReimbursement']</value>
      <webElementGuid>3cb2b456-b36a-430b-9f7e-33e42b6f5770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim item'])[1]/following::select[1]</value>
      <webElementGuid>9f630a40-62c4-4d84-843c-3b67818ecf9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of treatment'])[1]/following::select[1]</value>
      <webElementGuid>09c247da-7768-4c42-b784-36242ed1b8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are the hospitals under HA?'])[1]/preceding::select[1]</value>
      <webElementGuid>213ca728-93e0-4063-b8b5-0fd1c40d8880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3106e5ed-ea2d-4b6b-a5a4-6e63498d2161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'natureOfReimbursement' and @id = 'natureOfReimbursement' and (text() = 'Please selectGeneral PractitionerSpecialistPrescribed Western MedicationDiag. Imaging &amp; Lab TestsChinese HerbalistBonesetterPhysiotherapistChiropractorPrescribed Western Medication (Pharmacy)' or . = 'Please selectGeneral PractitionerSpecialistPrescribed Western MedicationDiag. Imaging &amp; Lab TestsChinese HerbalistBonesetterPhysiotherapistChiropractorPrescribed Western Medication (Pharmacy)')]</value>
      <webElementGuid>48d20515-8fa2-4dde-b234-a804a2940f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
