<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>805f5b2a-01de-425b-b387-b6593c75a61e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>145325c2-791f-4ebc-b6c5-388bc44a1612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-w-full tw-text-white tw-text-center tw-p-3 tw-bg-my-red-purple hover:tw-bg-my-red-purple-hover tw-mt-10 lg:tw-text-base tw-text-sm ng-isolate-scope</value>
      <webElementGuid>2197860b-5df7-4356-9c17-ae557ea5fceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ec49976-2bfd-4862-ae57-73e60ea984bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bupa-button-busy</name>
      <type>Main</type>
      <value>lc.isBusy</value>
      <webElementGuid>712a3f12-5134-4447-9e98-8e0329c0966f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>lc.goB2CLogin()</value>
      <webElementGuid>29d4a141-c7d4-4ed6-aeea-bba30560151c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Next
                        </value>
      <webElementGuid>d8be7860-8ce9-4093-83b4-39c7b2544edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row add-padding-bottom--small&quot;]/div[@class=&quot;welcome-page-background tw-font-light tw-font-gotham-book tw-bg-fixed&quot;]/div[@class=&quot;lg:tw-pt-20 lg:tw-pb-20 tw-pt-10 tw-pb-16 lg:tasdw-min-h-screen&quot;]/div[@class=&quot;tw-max-w-4xl tw-mx-auto tw-px-6&quot;]/div[@class=&quot;lg:tw-mt-20 tw-mt-10&quot;]/div[@class=&quot;tw-grid tw-grid-cols-12 lg:tw-gap-x-10&quot;]/div[@class=&quot;lg:tw-col-span-6 tw-col-span-12 lg:tw-py-10 tw-py-8 lg:tw-px-8 tw-px-6 tw-bg-white tw-max-w-sm tw-mx-auto tw-w-full tw-flex tw-flex-col tw-justify-between&quot;]/button[@class=&quot;tw-w-full tw-text-white tw-text-center tw-p-3 tw-bg-my-red-purple hover:tw-bg-my-red-purple-hover tw-mt-10 lg:tw-text-base tw-text-sm ng-isolate-scope&quot;]</value>
      <webElementGuid>18eb48a7-eb34-450f-9089-014bac50f3a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>48b15248-87bd-4f5f-9996-abb6528cac4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>ada4ebb3-4f5d-45b4-9bd4-accbf41bfbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual / Group member'])[1]/following::button[1]</value>
      <webElementGuid>ccf0b9da-e8c4-4811-affe-269ca11a0b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to myBupa - Insurance made easy'])[1]/following::button[1]</value>
      <webElementGuid>c03e0e33-73ad-40cc-8384-02962420cee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intermediaries / HRs log in'])[1]/preceding::button[1]</value>
      <webElementGuid>0b2518fa-ccee-4539-853c-3c6877becf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[2]/preceding::button[1]</value>
      <webElementGuid>13f41fc1-cb01-4ed1-9070-d390d060f6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>ff77cd2e-7752-400b-b5df-cf3a202a4f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>09af796e-17c1-4be1-84bd-3616b04c7b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                            Next
                        ' or . = '
                            Next
                        ')]</value>
      <webElementGuid>08563011-ceb1-4036-a13b-a2f25904cb42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
